# Site settings
exclude: [README.md,example1.md,example2.md]
title: Hui Su
email: aaronsu@tencent.com
scholar_id: IaliaJ0AAAAJ
description: > # this symbol means ignore newlines until "baseurl:"
    Hi! I'm Hui and here you will find what I do.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://suhui.github.io" # the base hostname & protocol for your site
#paginate: 3


# Build settings
markdown: kramdown
